/**
 * LY.com Inc.
 * Copyright (c) 2004-2016 All Rights Reserved.
 */package com.ly.report.tmc.datacollectionapi.dal.daointerface;
import com.ly.report.tmc.datacollectionapi.dal.dataobject.TaskDO;
import org.springframework.dao.DataAccessException;

/**
 * TaskDAO
 * database table: TASK
 * database table comments: Task
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public interface TaskDAO {


	/**
	 * 
	 * sql:
	 * <pre>select         *      FROM         TASK                  WHERE         ID = ?</pre> 
	 */
	public TaskDO selectById(Integer id) throws DataAccessException;

}



