/**
 * LY.com Inc.
 * Copyright (c) 2004-2016 All Rights Reserved.
 */
package com.ly.report.tmc.datacollectionapi.dal.dataobject;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;


import java.util.*;

/**
 * TaskDO
 * database table: TASK
 * database table comments: Task
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public class TaskDO implements java.io.Serializable {
	private static final long serialVersionUID = -5216457518046898601L;
	
	/**
	 * 主键Id 		db_column: ID 
	 */
	private int id;
	/**
	 * 父节点Id 		db_column: PARENTID 
	 */
	private int parentid;
	/**
	 * 任务名称 		db_column: NAME 
	 */
	private String name;
	/**
	 * 任务描述 		db_column: DESCRIPTION 
	 */
	private String description;
	/**
	 * 定时任务 执行表达式 		db_column: CORN 
	 */
	private String corn;
	/**
	 * 节点状态 		db_column: STATE 
	 */
	private int state;
	/**
	 * 创建时间 		db_column: CREATETIME 
	 */
	private Date createtime;

	
	public void setId(int id) {
		this.id = id;
	}
	
	public int getId() {
		return this.id;
	}
	
	public void setParentid(int parentid) {
		this.parentid = parentid;
	}
	
	public int getParentid() {
		return this.parentid;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public String getName() {
		return this.name;
	}
	
	public void setDescription(String description) {
		this.description = description;
	}
	
	public String getDescription() {
		return this.description;
	}
	
	public void setCorn(String corn) {
		this.corn = corn;
	}
	
	public String getCorn() {
		return this.corn;
	}
	
	public void setState(int state) {
		this.state = state;
	}
	
	public int getState() {
		return this.state;
	}
	
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}
	
	public Date getCreatetime() {
		return this.createtime;
	}

	public String toString() {
		return new ToStringBuilder(this)
			.append("Id",getId())
			.append("Parentid",getParentid())
			.append("Name",getName())
			.append("Description",getDescription())
			.append("Corn",getCorn())
			.append("State",getState())
			.append("Createtime",getCreatetime())
			.toString();
	}
	
	public int hashCode() {
		return new HashCodeBuilder()
			.append(getId())
			.toHashCode();
	}
	
	public boolean equals(Object obj) {
		if(obj == null) return false;
		if(this == obj) return true;
		if(obj instanceof TaskDO == false) return false;
		TaskDO other = (TaskDO)obj;
		return new EqualsBuilder()
			.append(getId(),other.getId())
			.isEquals();
	}
}

