/**
 * LY.com Inc.
 * Copyright (c) 2004-2016 All Rights Reserved.
 */
package com.ly.report.tmc.datacollectionapi.dal.dataobject;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;


import java.util.*;

/**
 * TaskNodeDO
 * database table: TASK_NODE
 * database table comments: TaskNode
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public class TaskNodeDO implements java.io.Serializable {
	private static final long serialVersionUID = -5216457518046898601L;
	
	/**
	 * id 		db_column: ID 
	 */
	private long id;
	/**
	 * 关联任务id 		db_column: TASKID 
	 */
	private long taskid;
	/**
	 * 节点名称 		db_column: NODE_NAME 
	 */
	private String nodeName;
	/**
	 * 节点状态 		db_column: NODE_STATE 
	 */
	private int nodeState;
	/**
	 * 节点类型 		db_column: NODE_TYPE 
	 */
	private int nodeType;
	/**
	 * 几点描述 		db_column: DESCRIPTION 
	 */
	private String description;
	/**
	 * createtime 		db_column: CREATETIME 
	 */
	private Date createtime;
	/**
	 * 执行次数 		db_column: COUNT 
	 */
	private int count;

	
	public void setId(long id) {
		this.id = id;
	}
	
	public long getId() {
		return this.id;
	}
	
	public void setTaskid(long taskid) {
		this.taskid = taskid;
	}
	
	public long getTaskid() {
		return this.taskid;
	}
	
	public void setNodeName(String nodeName) {
		this.nodeName = nodeName;
	}
	
	public String getNodeName() {
		return this.nodeName;
	}
	
	public void setNodeState(int nodeState) {
		this.nodeState = nodeState;
	}
	
	public int getNodeState() {
		return this.nodeState;
	}
	
	public void setNodeType(int nodeType) {
		this.nodeType = nodeType;
	}
	
	public int getNodeType() {
		return this.nodeType;
	}
	
	public void setDescription(String description) {
		this.description = description;
	}
	
	public String getDescription() {
		return this.description;
	}
	
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}
	
	public Date getCreatetime() {
		return this.createtime;
	}
	
	public void setCount(int count) {
		this.count = count;
	}
	
	public int getCount() {
		return this.count;
	}

	public String toString() {
		return new ToStringBuilder(this)
			.append("Id",getId())
			.append("Taskid",getTaskid())
			.append("NodeName",getNodeName())
			.append("NodeState",getNodeState())
			.append("NodeType",getNodeType())
			.append("Description",getDescription())
			.append("Createtime",getCreatetime())
			.append("Count",getCount())
			.toString();
	}
	
	public int hashCode() {
		return new HashCodeBuilder()
			.append(getId())
			.toHashCode();
	}
	
	public boolean equals(Object obj) {
		if(obj == null) return false;
		if(this == obj) return true;
		if(obj instanceof TaskNodeDO == false) return false;
		TaskNodeDO other = (TaskNodeDO)obj;
		return new EqualsBuilder()
			.append(getId(),other.getId())
			.isEquals();
	}
}

