/**
 * LY.com Inc.
 * Copyright (c) 2004-2016 All Rights Reserved.
 */ 
package com.ly.report.tmc.datacollectionapi.dal.ibatis;

import com.ly.report.tmc.datacollectionapi.dal.dataobject.TaskNodeDO;


import org.springframework.dao.DataAccessException;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.ly.report.tmc.datacollectionapi.dal.daointerface.TaskNodeDAO;

/**
 * TaskNodeDAO
 * database table: TASK_NODE
 * database table comments: TaskNode
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public class IbatisTaskNodeDAO extends SqlMapClientDaoSupport implements TaskNodeDAO {


	/**
	 * 
	 * sql: 
	 * <pre>select         *       FROM         TASK_NODE      WHERE         ID = ?</pre>
	 */
	public TaskNodeDO selectById(Long id) throws DataAccessException {
		return (TaskNodeDO)getSqlMapClientTemplate().queryForObject("datacollectionapi.TaskNode.selectById",id);
	}

}

